package reporter

import (
	"fmt"
	"html/template"
	"io"
	"strings"

	"github.com/sutekar/es2os/pkg/analyzer"
	"github.com/sutekar/es2os/pkg/scanner"
	"github.com/sutekar/es2os/pkg/transformer"
)

// HTMLReport generates a self-contained HTML report.
func HTMLReport(w io.Writer, scan *scanner.ScanResult, analysis *analyzer.AnalysisResult, transform *transformer.TransformResult) error {
	data := struct {
		SourceVersion string
		TargetVersion string
		TotalIndices  int
		TotalFields   int
		Analysis      *analyzer.AnalysisResult
		Transform     *transformer.TransformResult
		ByIndex       map[string][]analyzer.Finding
		CleanIndices  string
	}{
		SourceVersion: scan.SourceVersion,
		TargetVersion: scan.TargetVersion,
		TotalIndices:  len(scan.Indices),
		TotalFields:   scan.TotalFields,
		Analysis:      analysis,
		Transform:     transform,
		ByIndex:       groupByIndex(analysis.Findings),
		CleanIndices:  strings.Join(analysis.CleanIndices, ", "),
	}

	return htmlTmpl.Execute(w, data)
}

var funcMap = template.FuncMap{
	"severityClass": func(s analyzer.Severity) string {
		switch s {
		case analyzer.SeverityCritical:
			return "critical"
		case analyzer.SeverityWarning:
			return "warning"
		default:
			return "info"
		}
	},
	"severityIcon": func(s analyzer.Severity) string {
		switch s {
		case analyzer.SeverityCritical:
			return "❌"
		case analyzer.SeverityWarning:
			return "⚠️"
		default:
			return "ℹ️"
		}
	},
}

var htmlTmpl = template.Must(template.New("report").Funcs(funcMap).Parse(fmt.Sprintf(`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>es2os Migration Report</title>
<style>
%s
</style>
</head>
<body>
<div class="container">
<h1>es2os — Migration Compatibility Report</h1>
<div class="meta">
  <span class="badge source">Source: Elasticsearch {{.SourceVersion}}</span>
  <span class="badge target">Target: OpenSearch {{.TargetVersion}}</span>
</div>

<div class="summary-cards">
  <div class="card">
    <div class="card-number">{{.TotalIndices}}</div>
    <div class="card-label">Indices</div>
  </div>
  <div class="card">
    <div class="card-number">{{.TotalFields}}</div>
    <div class="card-label">Fields</div>
  </div>
  <div class="card card-green">
    <div class="card-number">{{len .Analysis.CleanIndices}}</div>
    <div class="card-label">Clean</div>
  </div>
  <div class="card card-red">
    <div class="card-number">{{.Analysis.CriticalCount}}</div>
    <div class="card-label">Critical</div>
  </div>
  <div class="card card-yellow">
    <div class="card-number">{{.Analysis.WarningCount}}</div>
    <div class="card-label">Warnings</div>
  </div>
</div>

<h2>Findings</h2>
{{range $index, $findings := .ByIndex}}
<div class="index-section">
  <h3>{{$index}}</h3>
  {{range $findings}}
  <div class="finding {{severityClass .Severity}}">
    <span class="icon">{{severityIcon .Severity}}</span>
    <strong>[{{.RuleID}}]</strong> {{.Title}}
    {{if .FieldName}}<span class="field">field: {{.FieldName}}</span>{{end}}
    <div class="action">{{if .AutoFix}}✅ Auto-fixable{{else}}→ {{.Action}}{{end}}</div>
  </div>
  {{end}}
</div>
{{end}}

{{if .CleanIndices}}
<div class="index-section clean">
  <h3>✅ Clean Indices</h3>
  <p>{{.CleanIndices}}</p>
</div>
{{end}}

{{if .Transform}}
<h2>Transform Preview</h2>
{{range $name, $ti := .Transform.Indices}}
{{if not $ti.Skipped}}{{if $ti.Changes}}
<div class="index-section">
  <h3>{{$name}}</h3>
  {{range $ti.Changes}}
  <div class="change">
    <strong>{{.FieldPath}}</strong>
    <div class="diff">
      <div class="before">- {{.Before}}</div>
      <div class="after">+ {{.After}}</div>
    </div>
  </div>
  {{end}}
</div>
{{end}}{{end}}
{{end}}
{{end}}

<footer>
  <p>Generated by <strong>es2os</strong> — <a href="https://github.com/sutekar/es2os">github.com/sutekar/es2os</a></p>
</footer>
</div>
</body>
</html>`, htmlCSS)))

const htmlCSS = `
* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #1a1a2e; color: #eaeaea; padding: 2em; }
.container { max-width: 900px; margin: 0 auto; }
h1 { color: #00d4aa; margin-bottom: 0.5em; }
h2 { color: #00d4aa; margin: 1.5em 0 0.5em; border-bottom: 1px solid #333; padding-bottom: 0.3em; }
h3 { color: #ccc; margin-bottom: 0.5em; }
.meta { margin-bottom: 1.5em; }
.badge { display: inline-block; padding: 0.3em 0.8em; border-radius: 4px; margin-right: 0.5em; font-size: 0.9em; }
.badge.source { background: rgba(255,217,61,0.2); color: #ffd93d; }
.badge.target { background: rgba(0,212,170,0.2); color: #00d4aa; }
.summary-cards { display: flex; gap: 1em; margin: 1em 0; flex-wrap: wrap; }
.card { background: rgba(255,255,255,0.05); border: 1px solid #333; border-radius: 8px; padding: 1em; text-align: center; min-width: 100px; }
.card-number { font-size: 2em; font-weight: bold; color: #eaeaea; }
.card-label { font-size: 0.8em; color: #888; }
.card-green .card-number { color: #00d4aa; }
.card-red .card-number { color: #ff6b6b; }
.card-yellow .card-number { color: #ffd93d; }
.index-section { background: rgba(255,255,255,0.03); border: 1px solid #333; border-radius: 8px; padding: 1em; margin: 0.8em 0; }
.index-section.clean { border-color: #00d4aa; }
.finding { padding: 0.5em; margin: 0.3em 0; border-left: 3px solid #333; padding-left: 1em; }
.finding.critical { border-color: #ff6b6b; }
.finding.warning { border-color: #ffd93d; }
.finding.info { border-color: #888; }
.finding .field { color: #888; font-size: 0.85em; margin-left: 0.5em; }
.finding .action { color: #888; font-size: 0.85em; margin-top: 0.3em; }
.change { margin: 0.5em 0; padding: 0.5em; }
.diff { font-family: monospace; font-size: 0.9em; margin-top: 0.3em; }
.before { color: #ff6b6b; }
.after { color: #00d4aa; }
footer { margin-top: 2em; padding-top: 1em; border-top: 1px solid #333; color: #888; font-size: 0.85em; }
footer a { color: #00d4aa; }
`
